name: Run Tests on PR

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build_package:
    name: Build and Package Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install NPM dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
